
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (<>

    <html lang="en">
      <head>

      </head>
      <body className={inter.className}>
        <div className="flex  h-lvh min-w-full">
          <nav className="p-4 bg-neutral-950 basis-1/5 h-full max-w-64 ">
            <ul className="flex flex-col gap-4">
              <li className="text-3xl example-style">|CAP$TONE</li>
              <li className="hover:bg-neutral-700 flex duration-200 rounded-sm"><Link className="h-full w-full p-2" href="/"> Dashboard</Link></li>
              <li className="hover:bg-neutral-700 flex duration-200 rounded-sm"><Link className="h-full w-full p-2" href="/networth"> Net Worth</Link></li>
              <li className="hover:bg-neutral-700 flex duration-200 rounded-sm"><Link className="h-full w-full p-2" href="/cashflow"> Cash Flow</Link></li>
              <li className="hover:bg-neutral-700 flex duration-200 rounded-sm"><Link className="h-full w-full p-2" href="/analytics"> Analytics</Link></li>

            </ul>
          </nav>
          <main className="grow basis-3/4 p-8 h-screen overflow-y-scroll pl-[5vw]">
            {children}
            <footer className="p-4 text-white b " >
              <p>CPSC 490 Capstone Project</p>
              <p>By Patrick Valera</p>
            </footer>
          </main>

        </div>
      </body>

    </html>
  </>

  );
}
